# **ANIRUDDHA GHOSH RA2011030010038**

**This program prints Hello, world!**

In [ ]:
print("Hello, world!")

Hello, world!

**This program adds two numbers**

In [ ]:
num1=int(input("Enter 1st number: "))
num2=int(input("Enter 2nd number: "))
sum=num1+num2
print(sum)

Enter 1st number: 3
Enter 2nd number: 5
8

**Python Program to calculate the square root**

In [ ]:
import math
num=int(input("Enter number: "))
new_number=math.sqrt(num)
print(int(new_number))

Enter number: 25
5

**Python Program to find the area of a triangle**

In [ ]:
import math
num1=int(input("Enter 1st side: "))
num2=int(input("Enter 2nd side: "))
num3=int(input("Enter 3rd side: "))
s=(num1+num2+num3)/2
area = s*(s-num1)*(s-num2)*(s-num3)
print(math.sqrt(area))

Enter 1st side: 3
Enter 2nd side: 4
Enter 3rd side: 5
6.0

**Solve the quadratic equation ax^2 + bx + c = 0**

In [ ]:
import math
a=int(input("Enter a value: "))
b=int(input("Enter b value: "))
c=int(input("Enter c value: "))
detector= math.sqrt((b**2)-(4*a*c))
res1=(-b+detector)/(2*a)
res2=(-b-detector)/(2*a)
print("Roots are " , res1 ," and ",res2 )

Enter a value: 10
Enter b value: 9
Enter c value: -1
Roots are  0.1  and  -1.0

**Python program to swap two variables**

In [ ]:
a=int(input("Enter a value: "))
b=int(input("Enter b value: "))
print("Prev a=",a ," b=",b )
a,b=b,a
print("Later a=",a ," b=",b )

Enter a value: 4
Enter b value: 5
Prev a= 4  b= 5
Later a= 5  b= 4

**Program to generate a random number between 0 and 9**

In [ ]:
import random
print(random.randint(1,9)) #1 <= N <= 9

5

**Taking kilometers input miles from the user**

In [ ]:
a=int(input("Enter km value: "))
print(a*0.621371)

Enter km value: 2
1.242742

**Python Program to convert temperature in celsius to Fahrenheit**

In [ ]:
a=int(input("Enter Celcious value: "))
value=(a*9/5)+32
print(value)

Enter Celcious value: 2
35.6

**Python program to check if the input number is odd or even**

In [ ]:
a=int(input("Enter value: "))
if(a%2==0):
  value=True
else:
  value=False
print(value)

Enter value: 6
True

**Python program to check if the year is a leap year or not**

In [ ]:
a=int(input("Enter year: "))
if(a%100==0 and a%400==0):
  value=True
elif(a%100!=0 and a%4==0):
  alue=True
else:
  value=False
print(value)

Enter year: 1500
False

**Python program to find the largest number among the three input numbers**

In [ ]:
a=int(input("Enter 1st num: "))
b=int(input("Enter 2nd num: "))
c=int(input("Enter 3rd num: "))
if(a>b and a>c):
  value=a
elif(b>a and b>c):
  value=b
else:
  value=c
print(value)

Enter 1st num: 5
Enter 2nd num: 7
Enter 3rd num: 6
7

**Program to check if a number is prime or not**

In [ ]:
a=int(input("Enter a Number"))
value=True
if(a==0 or a==1):
  value=False
else:
  for i in range (2,(int(a/2)+1)):
    if(a%i==0):
      value=False
print(value)

Enter a Number5
True

**Python program to display all the prime numbers within an interval**

In [ ]:
def isPrime(a):
    value=True
    if(a==0 or a==1):
            value=False
            return value
    else:
        for i in range (2,(int(a/2)+1)):
                if(a%i==0):
                    value=False
        return value
        
    
if __name__=="__main__":
    num1=int(input("Enter 1st interval: "))
    num2=int(input("Enter 2nd interval: "))
    print("Prime Numbers are ", end="")
    for i in range(num1,num2):
            result=isPrime(i)
            if result==True:
              print(str(i)+" , " ,end="")

Enter 1st interval: 1
Enter 2nd interval: 10
Prime Numbers are 2 , 3 , 5 , 7 ,

**Python program to find the factorial of a number provided by the user**

In [ ]:
num1=int(input("Enter number: "))
result=1
if(num1==1 or num1==0):
    result=1
elif(num1<0):
    print("Enter a positive value")
else:
    for i in range (1,num1+1):
            result=result*i;
print(result)

Enter number: 5
120

**Multiplication table (from 1 to 10) in Python**

In [ ]:
for i in range (1,11):
    for j in range(1,11):
            print(i," * ",j," is ",i*j)

1  *  1  is  1
1  *  2  is  2
1  *  3  is  3
1  *  4  is  4
1  *  5  is  5
1  *  6  is  6
1  *  7  is  7
1  *  8  is  8
1  *  9  is  9
1  *  10  is  10
2  *  1  is  2
2  *  2  is  4
2  *  3  is  6
2  *  4  is  8
2  *  5  is  10
2  *  6  is  12
2  *  7  is  14
2  *  8  is  16
2  *  9  is  18
2  *  10  is  20
3  *  1  is  3
3  *  2  is  6
3  *  3  is  9
3  *  4  is  12
3  *  5  is  15
3  *  6  is  18
3  *  7  is  21
3  *  8  is  24
3  *  9  is  27
3  *  10  is  30
4  *  1  is  4
4  *  2  is  8
4  *  3  is  12
4  *  4  is  16
4  *  5  is  20
4  *  6  is  24
4  *  7  is  28
4  *  8  is  32
4  *  9  is  36
4  *  10  is  40
5  *  1  is  5
5  *  2  is  10
5  *  3  is  15
5  *  4  is  20
5  *  5  is  25
5  *  6  is  30
5  *  7  is  35
5  *  8  is  40
5  *  9  is  45
5  *  10  is  50
6  *  1  is  6
6  *  2  is  12
6  *  3  is  18
6  *  4  is  24
6  *  5  is  30
6  *  6  is  36
6  *  7  is  42
6  *  8  is  48
6  *  9  is  54
6  *  10  is  60
7  *  1  is  7
7  *  2  is  14
7  *  3  is  21
7  *  4  is  28
7  *  5  is  35
7  *  6  is  42
7  *  7  is  49
7  *  8  is  56
7  *  9  is  63
7  *  10  is  70
8  *  1  is  8
8  *  2  is  16
8  *  3  is  24
8  *  4  is  32
8  *  5  is  40
8  *  6  is  48
8  *  7  is  56
8  *  8  is  64
8  *  9  is  72
8  *  10  is  80
9  *  1  is  9
9  *  2  is  18
9  *  3  is  27
9  *  4  is  36
9  *  5  is  45
9  *  6  is  54
9  *  7  is  63
9  *  8  is  72
9  *  9  is  81
9  *  10  is  90
10  *  1  is  10
10  *  2  is  20
10  *  3  is  30
10  *  4  is  40
10  *  5  is  50
10  *  6  is  60
10  *  7  is  70
10  *  8  is  80
10  *  9  is  90
10  *  10  is  100

**Program to display the Fibonacci sequence up to nth term**

In [ ]:
import array as arr
num=int(input("Enter number: "))
a = arr.array('i', [0,1])
if(num==0):
    print(0)
elif (num==1):
    print(1)
else:
    for i in range(2,num):
            sum=a[i-1]+a[i-2]
            a.append(sum)
    for j in (a):
            print (j, end =" ")

Enter number: 5
0 1 1 2 3

**Python program to check if the number is an Armstrong number or not**

In [ ]:
num=int(input("Enter number: "))
num1=num
str1=str(num)
lenth=len(str1)
total=0
while num>0:
    temp=num%10
    total=total+temp**lenth
    num=num//10
if(total==num1):
    print("Armstrong number")
else:
    print("Not Armstrong number")

Enter number: 153
Armstrong number

**Program to check Armstrong numbers in a certain interval**

In [ ]:
def isArmstrong(num):
    num1=num
    str1=str(num)
    lenth=len(str1)
    total=0
    while num>0:
            temp=num%10
            total=total+temp**lenth
            num=num//10
    if(total==num1):
            return True
    else:
            return False

if __name__== "__main__":
    num1=int(input("Enter 1st number: "))
    num2=int(input("Enter 2nd number: "))
    print("Armstrong Numbers are ")
    for i in range(num1,num2):
            result=isArmstrong(i)
            if(result):
              print(str(i)+" , ",end="")

Enter 1st number: 300
Enter 2nd number: 400
Armstrong Numbers are
370 , 371 ,

**Sum of natural numbers up to num**

In [ ]:
num=int(input("Enter number: "))
suum=int((num*(num+1))/2)
print(suum)

Enter number: 10
55

**Display the powers of 2 using an anonymous function**

In [ ]:
print("Enter Number of Term: ", end="")
tot = int(input())
anoms = lambda x: 2 ** x #Anonymous Function
print()
for i in range(tot):
    print("2 raised to the power ", i, " is ", anoms(i))

Enter Number of Term: 5

2 raised to the power  0  is  1
2 raised to the power  1  is  2
2 raised to the power  2  is  4
2 raised to the power  3  is  8
2 raised to the power  4  is  16

**Take a list of numbers**

In [ ]:
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
for i in thislist:
    print(i)

apple
banana
cherry
apple
cherry

 **Python program to convert decimal into other number systems**

In [ ]:
num=int(input("Enter a number: "))
print("The decimal value of", num, "is:")
print(bin(num), "in binary.")
print(oct(num), "in octal.")
print(hex(num), "in hexadecimal.")

Enter a number: 10
The decimal value of 10 is:
0b1010 in binary.
0o12 in octal.
0xa in hexadecimal.

**Program to find the ASCII value of the given character**

In [ ]:
K = input("Please enter a character: ")    
print ("The ASCII value of '" + K + "' is ", ord(K))

Please enter a character: a
The ASCII value of 'a' is  97